### ISSUE TITLE
nextStep en operacion "dolar"

### ISSUE THREAD

**Issue by FranElfers** [FranElfers/tiger-bot#2]
La operacion "dolar" no deberia tener la función "nextStep" ya que solo tiene 1 paso.
```log
2023-05-15 10:32:26.798 [info ] [Tiger] Starting bot
2023-05-15 10:32:26.814 [info ] [Tiger] [express] listening on 3001
2023-05-15 10:32:28.138 [info ] [Tiger] [operator:start] {"command":"feedback","user":{"id":6287146153,"name":"Valery Montenegro"}}
2023-05-15 10:32:28.140 [info ] [Tiger] [operation:6287146153] Starting new feedback
2023-05-15 10:32:28.141 [info ] [Tiger] [operator:start] {"command":"feedback","user":{"id":6287146153,"name":"Valery Montenegro"}}
2023-05-15 10:32:28.142 [info ] [Tiger] [operation:6287146153] Closing feedback
2023-05-15 10:32:28.143 [info ] [Tiger] [operation:6287146153] Starting new feedback
2023-05-15 10:32:28.148 [info ] [Tiger] [operator:start] {"command":"dolar","user":{"id":6287146153,"name":"Valery Montenegro"}}
2023-05-15 10:32:28.150 [info ] [Tiger] [operation:6287146153] Closing feedback
2023-05-15 10:32:28.150 [info ] [Tiger] [operation:6287146153] Starting new dolar
2023-05-15 10:32:28.159 [info ] [Tiger] [operator:nextStep] {"user":{"id":6287146153,"name":"Valery Montenegro"}}
2023-05-15 10:32:28.161 [info ] [Tiger] [operation:6287146153] dolar step: 1
D:\Proyectos\tiger-bot\dist\src\operation.js:43
            currentCommand(ctx);
            ^

TypeError: currentCommand is not a function
    at Operation.<anonymous> (D:\Proyectos\tiger-bot\dist\src\operation.js:43:13)
    at Generator.next (<anonymous>)
    at D:\Proyectos\tiger-bot\dist\src\operation.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\tiger-bot\dist\src\operation.js:4:12)
    at Operation.nextStep (D:\Proyectos\tiger-bot\dist\src\operation.js:38:16)
    at Object.<anonymous> (D:\Proyectos\tiger-bot\dist\src\operator.js:44:34)
    at Generator.next (<anonymous>)
    at D:\Proyectos\tiger-bot\dist\src\operator.js:8:71
    at new Promise (<anonymous>)

Node.js v18.15.0
```

**Comment by FranElfers** [comment]
La causa de este problema es cuando el bot está apagado, se le envían dos mensajes seguidos, un comando de 1 solo paso y un texto convencional:

![image](https://github.com/FranElfers/tiger-bot/assets/39459727/2ee6d932-47a3-423d-b438-c79967712daa)

Al iniciarse el bot, lee los mensajes instantáneamente, primero el comando /dolar y luego el texto. Al leer el comando dolar, para completar el primer y único paso necesita realizar una llamada a la base de datos:

![image](https://github.com/FranElfers/tiger-bot/assets/39459727/57d7e8e3-77a5-4ffe-aa4d-fcba99d02f7c)

Esto puede tardar un pequeño instante, y al ser un proceso asíncrono, el proceso sigue con el texto del segundo mensaje.

Si se recibe un texto, siempre que haya un comando activo se va a ejecutar `Operator.nextStep()`.

![image](https://github.com/FranElfers/tiger-bot/assets/39459727/b7b61072-768f-49a9-a760-d44ae62e1cb4)

Y como no hay nextStep en la operacion "dolar", rompe.
